CREATE TABLE IF NOT EXISTS CATEGORY(
    ID_CATEGORY INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (100)
    );

INSERT INTO CATEGORY VALUES (NULL, 'Programação em Front-end');
INSERT INTO CATEGORY VALUES (NULL, 'Programação em Back-end');
INSERT INTO CATEGORY VALUES (NULL, 'Programação em Mobile');