CREATE TABLE IF NOT EXISTS SECTION(
    ID_SECTION INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (50),
    UPDATED_AT DATE,
    AUTHOR VARCHAR (50),
    ID_CATEGORY INTEGER,
    FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
);

INSERT INTO SECTION VALUES (NULL, 'Angular',NULL,'João Lucas', 1);
INSERT INTO SECTION VALUES (NULL, 'Java',NULL ,'Alisson',2);
INSERT INTO SECTION VALUES (NULL, 'React',NULL ,'Breno',1);